### REGISTER USER
POST http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "name" : "Franchisor 2",
  "email" : "franchisor2@frency.io",
  "password" : "Franchisor",
  "role" : "Franchisor"
}

### LOGIN USER
POST https://frency-api-ofjpwfxlpa-et.a.run.app/users/login
Content-Type: application/json
Accept: application/json

{
  "email" : "franchisor@frency.io",
  "password" : "franchisor"
}

### GET ALL USERS
GET http://localhost:8080/users
Content-Type: application/json
Accept: application/json
Authorization: c531f211-2cd1-4a98-b0d8-b7abe56ef2d6

### GET CURRENT USER
GET http://localhost:8080/users/current
Content-Type: application/json
Accept: application/json
Authorization: c531f211-2cd1-4a98-b0d8-b7abe56ef2d6

### EDIT CURRENT USER
PATCH http://localhost:8080/users/current
Content-Type: application/json
Accept: application/json
Authorization: c531f211-2cd1-4a98-b0d8-b7abe56ef2d6

{
  "name" : "string1",
  "email" : "john@example.com",
  "password" : "string1",
  "role" : "string1"
}

### LOGOUT
DELETE http://localhost:8080/users/logout
Content-Type: application/json
Accept: application/json
Authorization: c531f211-2cd1-4a98-b0d8-b7abe56ef2d6



### POST FRANCHISE
POST http://localhost:8080/franchises
Content-Type: application/json
Accept: application/json
Authorization: c531f211-2cd1-4a98-b0d8-b7abe56ef2d6

{
  "franchise_name" : "string",
  "address" : "string",
  "description" : "string",
  "category" : "string",
  "whatsapp_number" : "string",
  "franchiseType": [1]
}

### UPLOAD FRANCHISE GALLERY
POST http://localhost:8080/franchises/3/upload
Content-Type: multipart/form-data
Authorization: c531f211-2cd1-4a98-b0d8-b7abe56ef2d6

{
  "gallery" : ["img1.jpg", "img2.jpg", "img2.jpg"]
}

### GET ALL FRANCHISES
GET https://frency-api-ofjpwfxlpa-et.a.run.app/franchises
Content-Type: application/json
Accept: application/json
Authorization: 24b9e834-f6a3-47c8-a8fb-0d453134f3ce

### GET MY FRANCHISES
GET https://frency-api-ofjpwfxlpa-et.a.run.app/my_franchises
Content-Type: application/json
Accept: application/json
Authorization: 24b9e834-f6a3-47c8-a8fb-0d453134f3ce

### GET A FRANCHISE
GET http://localhost:8080/franchises/1
Content-Type: application/json
Accept: application/json
Authorization: 583afdc2-7cb6-4453-bf4d-19fd0f94a95f

### UPDATE FRANCHISE
PUT http://localhost:8080/franchises/3
Content-Type: application/json
Accept: application/json
Authorization: c531f211-2cd1-4a98-b0d8-b7abe56ef2d6

{
  "franchise_name" : "string 1",
  "address" : "string 1",
  "description" : "string 1",
  "category" : "string 1",
  "whatsapp_number" : "string 1",
  "franchiseType": [1, 3]
}

### DELETE FRANCHISE
DELETE http://localhost:8080/franchises/3
Content-Type: application/json
Accept: application/json
Authorization: c531f211-2cd1-4a98-b0d8-b7abe56ef2d6

### SEARCH FRANCHISES
GET http://localhost:8080/franchises/search?franchise_name=fr
Content-Type: application/json
Accept: application/json
Authorization: 583afdc2-7cb6-4453-bf4d-19fd0f94a95f