### REGISTER USER
POST http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "name" : "string2",
  "email" : "john@asessaxamsple.com",
  "password" : "string2",
  "role" : "string2"
}

### LOGIN USER
POST http://localhost:8080/users/login
Content-Type: application/json
Accept: application/json

{
  "email" : "john@asessaxamsple.com",
  "password" : "string2"
}

### GET ALL USERS
GET http://localhost:8080/users
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

### GET CURRENT USER
GET http://localhost:8080/users/current
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

### EDIT CURRENT USER
PATCH http://localhost:8080/users/current
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

{
  "name" : "string1",
  "email" : "john@example.com",
  "password" : "string1",
  "role" : "string1"
}

### LOGOUT
DELETE http://localhost:8080/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c



### POST FRANCHISE
POST http://localhost:8080/franchises
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

{
  "franchise_name" : "string",
  "address" : "string",
  "description" : "string",
  "category" : "string",
  "whatsapp_number" : "string",
  "franchiseType": [1, 2, 3]
}

### UPLOAD FRANCHISE GALLERY
POST http://localhost:8080/franchises/3/upload
Content-Type: multipart/form-data
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

{
  "gallery" : ["img1.jpg", "img2.jpg", "img2.jpg"]
}

### GET ALL FRANCHISES
GET http://localhost:8080/franchises
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

### GET MY FRANCHISES
GET http://localhost:8080/my_franchises
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

### GET A FRANCHISE
GET http://localhost:8080/franchises/2
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

### UPDATE FRANCHISE
PUT http://localhost:8080/franchises/3
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

{
  "franchise_name" : "string 1",
  "address" : "string 1",
  "description" : "string 1",
  "category" : "string 1",
  "whatsapp_number" : "string 1",
  "franchiseType": [1, 3]
}

### DELETE FRANCHISE
DELETE http://localhost:8080/franchises/3
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c

### SEARCH FRANCHISES
GET http://localhost:8080/franchises
Content-Type: application/json
Accept: application/json
Authorization: 581e468e-b0d9-4e44-8f0e-15e66cb1851c